---
title: "USPTO Exploration"
output: html_document
date: "2024-02-13"
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
```

Loading coded 
```{r}
library(arrow)
library(tidyverse)
library(lubridate)

data_path <- "/Users/aoluwolerotimi/Datasets/" # AO Changed file path
applications <- read_feather(paste0(data_path,"app_data_starter_coded.feather"))
```
clean the columns

```{r}
columns_with_x_suffix <- grep("\\.x$", names(applications), value = TRUE)

names(applications)[names(applications) %in% columns_with_x_suffix] <- sub("\\.x$", '', columns_with_x_suffix)


applications <- applications %>% select(-ends_with(".y"))
```

variable creation

```{r}
#quarter 
applications <- applications %>%
  mutate(
    quarter = paste0(year(filing_date), "/", quarter(filing_date)),
  )

# Aggregate applications by quarter and examiner
applications <- applications %>%
  group_by(quarter, examiner_id) %>%
  mutate(new_applications = n_distinct(application_number)) %>%
  ungroup()

applications <- applications %>%
  group_by(quarter, examiner_id) %>%
  mutate(ISSUED_applications = sum(disposal_type == "ISS" & !duplicated(application_number)))

applications <- applications %>%
  group_by(quarter, examiner_id) %>%
  mutate(abn_applications = sum(disposal_type == "ABN" & !duplicated(application_number)))

applications <- applications %>%
  group_by(quarter, examiner_id) %>%
  mutate(PEN_applications = sum(disposal_type == "PEND" & !duplicated(application_number)))

applications <- applications %>%
  group_by(quarter,examiner_art_unit) %>%
  mutate(examiner_art_unit_num =  n_distinct(examiner_id))%>%
  ungroup()
```

```{r}
max_quarter <- "2017/1"

# separation_indicator
applications <- applications %>%
  group_by(examiner_id) %>%
  mutate(max_quarter_examiner = max(quarter)) %>%
  ungroup() %>%
  mutate(separation_indicator = if_else(max_quarter_examiner < max_quarter, 1, 0))

applications <- applications[, !(names(applications) == "max_quarter_examiner")]
```

```{r}
#au_move_indicator
applications <- applications %>%
  group_by(examiner_id) %>%
  mutate(au_move_indicator = if_else(examiner_art_unit != lag(examiner_art_unit), 1, 0)) %>%
  ungroup()

applications <- applications %>%
  mutate(au_move_indicator = if_else(is.na(au_move_indicator), 0, au_move_indicator))
```

```{r}
# get the count of au_moves by quarter
applications <- applications %>%
  group_by(examiner_id, quarter) %>%
  mutate(
    au_moves = sum(au_move_indicator)
  ) %>%
  ungroup()
```

```{r}
columns_to_exclude <- c(
  "examiner_art_unit", "examiner_art_unit_num",
  "women_in_art_unit"
) # Due to a high number of missing vlaue in the gender value, the quality of the women_in_art_unit is poor, thus excluded

df <- applications[, !(names(applications) %in% columns_to_exclude)]
colSums(is.na(df))
```

```{r}
length(unique(df$tc)) # only 4 unique TCs in the data
```

```{r}
library(dplyr)
```

```{r}
# Step 1 & 2: Group by examiner_id and check for multiple unique 'tc' values
examiner_variation <- df %>%
  group_by(examiner_id) %>%
  summarise(tc_changes = n_distinct(tc) > 1) %>%
  ungroup()

# Step 3: Calculate the proportion of examiners with changing 'tc' values
proportion_changes <- mean(examiner_variation$tc_changes)

# Print the proportion
print(proportion_changes) # 0.0598336 of the examiners change TCs. We could subest to only those with constant TCs
# OR for the ones that changed TC, we could take their majority TC
```


```{r}
length(unique(df$uspc_subclass)) 
```


```{r}
# Group by examiner_id and calculate the number of unique uspc_classes
examiner_uspc_counts <- df %>%
  group_by(examiner_id) %>%
  summarise(unique_uspc_classes = n_distinct(uspc_class)) %>%
  ungroup()

# View the results
print(examiner_uspc_counts)

```




